# -*- coding: utf-8 -*-
"""Nearest Coffee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnaB7PhQ2ETqcw651r9Hy960cV1yGcmK
"""

import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import folium
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
warnings.filterwarnings('ignore')

metros = pd.read_excel('riyadh_metro_stations_Full.xlsx')
cafes = pd.read_excel('riyadh_cafes_and_bakeries.xlsx')

# Show first 5 rows
riyadh_utilites = pd.concat([metros, cafes], axis=0)
riyadh_utilites.head()

"""#EDA"""

# Show the shape of dataset - # of columns and rows
print('Number of columns and rows: \n')
print(riyadh_utilites.shape)

# Info about the dataset elements
print(riyadh_utilites.info())

# Description of the dataset
print(riyadh_utilites['Rating'].describe())

# Null values
print(riyadh_utilites.isnull().sum())

# Null values - there was no rating for these stations which is fine
riyadh_utilites[riyadh_utilites['Rating'] == 0]

# Show available types of Utilities
riyadh_utilites.value_counts('Type_of_Utility')

"""# Data Preprocessing"""

# removal of irrelevant utilities
riyadh_activities = riyadh_utilites[(riyadh_utilites['Type_of_Utility'] == 'cafe') | (riyadh_utilites['Type_of_Utility'] == 'Metro Station')]

# check null values
print(riyadh_activities.isnull().sum())
# check where nulls pertains
riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'].isnull().sum() # null values will stay as they are not important for metros

riyadh_activities['name_coordinates'] = riyadh_activities['Name'] + riyadh_activities['Latitude'].astype(str) + ',' + riyadh_activities['Longitude'].astype(str)

"""### Information about latitude and longitude:

---

latitude and longitude, in cartography, a coordinate system used to determine and describe the position of any place on Earth’s surface. **Latitude** is a measurement of a location north or south of the Equator. In contrast, **longitude** is a measurement of location east or west

## Map Visualization
"""

# Create a Folium map centered around Riyadh
combined_map = folium.Map(location=[24.7476029,46.8309389 ], zoom_start=15)

# Add markers for cafes (Green icons)
'''
for i in range(0,len(riyadh_activities[(riyadh_activities['Type_of_Utility'] == 'cafe') & (riyadh_activities['Rating']>= 4)])):
    folium.Marker(
        location=[riyadh_activities[(riyadh_activities['Type_of_Utility'] == 'cafe') & (riyadh_activities['Rating'] >= 4)].iloc[i]['Latitude'], riyadh_activities[riyadh_activities['Type_of_Utility'] == 'cafe'].iloc[i]['Longitude']],
        popup=riyadh_activities[riyadh_activities['Type_of_Utility'] == 'cafe'].iloc[i]['Name'],
        icon = folium.Icon(color='green', icon='info-sign') # Ensure correct icon parameters
    ).add_to(combined_map)
'''
# Add markers for metro stations (Blue icons)
for i in range(0,len(riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'])):
    folium.Marker(
        location=[riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'].iloc[i]['Latitude'], metros.iloc[i]['Longitude']],
        popup=riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'].iloc[i]['name_coordinates'],
        icon = folium.Icon(color='blue', icon='info-sign') # Ensure correct icon parameters
    ).add_to(combined_map)

# Add home coordinates

folium.Marker(

 location=[24.7476029,46.8309389],
 popup='Home',
 icon = folium.Icon(color='black', icon='info-sign') # Ensure correct icon parameters
    ).add_to(combined_map)

# Ploygon of U walk
locations = [[24.736184381506888, 46.63128816610638],
             [24.740706763481242, 46.6313090055414],
             [24.74050213831618, 46.626041147565566],
             [24.73727681146874, 46.62577292669105]]
folium.Polygon(
    locations=locations,
    color='red',
    fill=True,
    fill_color='red',
    fill_opacity=0.2,
    tooltip="U walk"
).add_to(combined_map)

import folium

# Define the two locations (e.g., London and Paris)
ortangeline_start = (24.722187657827494, 46.86136479930703)
ortangeline_end = (24.591681192286366, 46.543570713656734)


# Add markers for London and Paris
folium.Marker(location=ortangeline_start, popup='Khashm Al An').add_to(combined_map)
folium.Marker(location=ortangeline_end, popup='Jeddah Road').add_to(combined_map)

# Add a blue line connecting London and Paris
folium.PolyLine(locations=[ortangeline_start, ortangeline_end], color='orange', weight=10, opacity=1).add_to(combined_map)

# Save the map to an HTML file
combined_map